;/*FB_PKG_DELIM*/

__d("PolarisAIContextLayerDialogQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27200895916210849"}),null);
__d("PolarisAIContextLayerDialogQuery$Parameters",["PolarisAIContextLayerDialogQuery_instagramRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PolarisAIContextLayerDialogQuery_instagramRelayOperation"),metadata:{is_fully_www_executable:!0},name:"PolarisAIContextLayerDialogQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PolarisAIContextLayerDialog.entrypoint",["JSResourceForInteraction","PolarisAIContextLayerDialogQuery$Parameters"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.mediaId;return{queries:{queryRef:{parameters:r("PolarisAIContextLayerDialogQuery$Parameters"),variables:{mediaId:e}}}}},root:r("JSResourceForInteraction")("PolarisAIContextLayerDialog.react").__setRef("PolarisAIContextLayerDialog.entrypoint")};l.default=e}),98);
__d("PolarisCreationEditRootQuery$Parameters",[],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:"27928576103429704",metadata:{is_fully_www_executable:!0},name:"PolarisCreationEditRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PolarisCreationEditRoot.entrypoint",["JSResourceForInteraction","PolarisCreationEditRootQuery$Parameters","polarisLongFormVideoCreationEntryPointVariables"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{queries:{polarisCreationEditRootQuery:{options:{fetchPolicy:"network-only"},parameters:r("PolarisCreationEditRootQuery$Parameters"),variables:{include_longform_clip_metadata:o("polarisLongFormVideoCreationEntryPointVariables").polarisLongFormClipMetadataUIEnabled(),shortcode:t.routeParams.shortcode}}}}},root:r("JSResourceForInteraction")("PolarisCreationEditRoot.react").__setRef("PolarisCreationEditRoot.entrypoint")};l.default=e}),98);
__d("PolarisLOXBlockRestrictUpsellCheck",["PolarisConfig","PolarisUA"],(function(t,n,r,o,a,i,l){"use strict";function e(){return!(!o("PolarisConfig").isLoggedOutUser()||o("PolarisUA").isTablet())}l.default=e}),98);
__d("PolarisRelationshipActionFavoriteUser",["PolarisInstapi","polarisLogAction"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t){return async function(n,a){r("polarisLogAction")("addFavoriteInFeedAttempt"),n({subjectUserId:e,type:"ADD_FEED_FAVORITE"}),await o("PolarisInstapi").apiPost("/api/v1/friendships/update_feed_favorites/",{body:{add:"["+e+"]",remove:[],source:t}}).then(function(t){var o=t.data;o?(r("polarisLogAction")("addFavoriteInFeedSuccess"),n({subjectUserId:e,type:"ADD_FEED_FAVORITE_SUCCEEDED"})):(r("polarisLogAction")("addFavoriteInFeedFailure"),n({subjectUserId:e,type:"ADD_FEED_FAVORITE_FAILED"}))})}}l.favoriteUser=e}),98);
__d("PolarisRelationshipActionUnfavoriteUser",["PolarisInstapi","polarisLogAction"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t){return async function(n,a){r("polarisLogAction")("removeFavoriteInFeedAttempt"),n({subjectUserId:e,type:"REMOVE_FEED_FAVORITE"}),await o("PolarisInstapi").apiPost("/api/v1/friendships/update_feed_favorites/",{body:{add:[],remove:"["+e+"]",source:t}}).then(function(t){r("polarisLogAction")("removeFavoriteInFeedSuccess");var o=t.data;o?n({subjectUserId:e,type:"REMOVE_FEED_FAVORITE_SUCCEEDED"}):(r("polarisLogAction")("removeFavoriteInFeedFailure"),n({subjectUserId:e,type:"REMOVE_FEED_FAVORITE_FAILED"}))})}}l.unfavoriteUser=e}),98);